In [5]:
from transformers import AutoTokenizer
from datasets import load_dataset

In [2]:
dataset = load_dataset("hans")

Downloading: 5.22kB [00:00, 1.13MB/s]                   
Downloading: 2.65kB [00:00, 1.26MB/s]                   
Downloading: 15.5MB [00:00, 103MB/s] 
Downloading: 15.5MB [00:00, 105MB/s]
                                           Dataset hans downloaded and prepared to /home/macab/.cache/huggingface/datasets/hans/plain_text/1.0.0/1bbcb735c482acd54f2e118074b59cfd2bf5f7a5a285d4d540d1e632216672ac. Subsequent calls will reuse this data.


In [7]:
set(dataset['train']['heuristic'])

{'constituent', 'lexical_overlap', 'subsequence'}

In [8]:
imdb = load_dataset("imdb")

Downloading: 4.75kB [00:00, 2.08MB/s]                   
Downloading: 2.17kB [00:00, 1.55MB/s]                   
                                           Dataset imdb downloaded and prepared to /home/macab/.cache/huggingface/datasets/imdb/plain_text/1.0.0/e3c66f1788a67a89c7058d97ff62b6c30531e05b549de56d3ab91891f0561f9a. Subsequent calls will reuse this data.


In [13]:
imdb

DatasetDict({
    train: Dataset({
        features: ['label', 'text'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['label', 'text'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['label', 'text'],
        num_rows: 50000
    })
})

In [10]:
set(imdb['train']['label'])

{0, 1}

In [13]:
sst2 = load_dataset("glue", "sst2")

NameError: name 'load_dataset' is not defined

In [14]:
sst2

DatasetDict({
    train: Dataset({
        features: ['idx', 'label', 'sentence'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['idx', 'label', 'sentence'],
        num_rows: 872
    })
    test: Dataset({
        features: ['idx', 'label', 'sentence'],
        num_rows: 1821
    })
})

In [16]:
set(sst2['train']['label'])

{0, 1}

In [17]:
sst2 = sst2.rename_column("sentence", "text")

In [18]:
sst2

DatasetDict({
    train: Dataset({
        features: ['idx', 'label', 'text'],
        num_rows: 67349
    })
    validation: Dataset({
        features: ['idx', 'label', 'text'],
        num_rows: 872
    })
    test: Dataset({
        features: ['idx', 'label', 'text'],
        num_rows: 1821
    })
})

In [20]:
import torch

In [45]:
softmax_outputs = torch.randn((2, 2)).softmax(dim=-1)

In [46]:
softmax_outputs

tensor([[0.1517, 0.8483],
        [0.1810, 0.8190]])

In [47]:
index = torch.tensor([1, 0])

In [48]:
index.shape

torch.Size([2])

In [53]:
torch.index_select(
    input=softmax_outputs,
    dim=-1,
    index=index
)

tensor([[0.8483, 0.1517],
        [0.8190, 0.1810]])

In [57]:
softmax_outputs.select(dim=0, index=0)

tensor([0.1517, 0.8483])

In [58]:
softmax_outputs.inde

Docstring:
index_select(dim, index) -> Tensor

See :func:`torch.index_select`
Type:      builtin_function_or_method


In [1]:
from dataset.loader import create_loaders
from transformers import AutoTokenizer
from datasets import load_dataset
from config import config
from dataset.imdb_sst2 import imdb_sst2_datasets, imdb_sst2_loaders

In [2]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

In [3]:
dsets = imdb_sst2_datasets(config=config['tasks']["imdb_sst2_sa"])
loaders = imdb_sst2_loaders(
    dataset=dsets,
    config=config['tasks']["imdb_sst2_sa"],
    tokenizer=tokenizer
)

Reusing dataset glue (/home/macab/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad)
Reusing dataset imdb (/home/macab/.cache/huggingface/datasets/imdb/plain_text/1.0.0/e3c66f1788a67a89c7058d97ff62b6c30531e05b549de56d3ab91891f0561f9a)
Loading cached shuffled indices for dataset at /home/macab/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-7210b288bf8eb0dc.arrow
Loading cached processed dataset at /home/macab/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-49d8e3e9a0228e21.arrow
100%|██████████| 25/25 [00:00<00:00, 38.20ba/s]
Loading cached processed dataset at /home/macab/.cache/huggingface/datasets/glue/sst2/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad/cache-1f5c072472e10b9b.arrow
100%|██████████| 25/25 [00:00<00:00, 49.78ba/s]
Loading cached shuffled indices for datas

In [6]:
batch = next(iter(loaders[domain]['train']))

In [9]:
tokenizer.decode((batch['input_ids'][0]), skip_special_tokens=True)

'cut through the layers of soap - opera emotion and you find a scathing portrayal of a powerful entity strangling the life out of the people who want to believe in it the most'

In [10]:
 for domain in loaders:

        for set in loaders[domain]:

            print(f'domain = {domain} | set = {set} | len = {len(loaders[domain][set])}')

domain = imdb | set = train | len = 6250
domain = imdb | set = valid | len = 214
domain = imdb | set = test | len = 214
domain = sst2 | set = train | len = 6250
domain = sst2 | set = valid | len = 214
domain = sst2 | set = test | len = 214


In [11]:
from transformers import AutoModel

In [12]:
model = AutoModel.from_pretrained('albert-base-v2')

Downloading: 100%|██████████| 684/684 [00:00<00:00, 414kB/s]
Downloading: 100%|██████████| 47.4M/47.4M [00:05<00:00, 8.86MB/s]
Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertModel: ['predictions.LayerNorm.bias', 'predictions.bias', 'predictions.dense.bias', 'predictions.decoder.weight', 'predictions.LayerNorm.weight', 'predictions.dense.weight', 'predictions.decoder.bias']
- This IS expected if you are initializing AlbertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing AlbertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [13]:
model

AlbertModel(
  (embeddings): AlbertEmbeddings(
    (word_embeddings): Embedding(30000, 128, padding_idx=0)
    (position_embeddings): Embedding(512, 128)
    (token_type_embeddings): Embedding(2, 128)
    (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0, inplace=False)
  )
  (encoder): AlbertTransformer(
    (embedding_hidden_mapping_in): Linear(in_features=128, out_features=768, bias=True)
    (albert_layer_groups): ModuleList(
      (0): AlbertLayerGroup(
        (albert_layers): ModuleList(
          (0): AlbertLayer(
            (full_layer_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (attention): AlbertAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (attention_dropout): Dropout(p=0, inplace=False)
      

In [18]:
modules = [model.embeddings, *model.albert_layer_groups[:6]]

AttributeError: 'AlbertModel' object has no attribute 'albert_layer_groups'